import 'package:flutter/material.dart';

List<Map> quesBank = [
  {
    'id': 1,
    'qus':
        "1. In the Flim \"OMG Oh My God\" Kanji BHai filed a case against whom for the damage of his shop due to an earthquake ?",
    'trueAns': "D. Bhagwan",
    'A': "A. Bharat Mata",
    'B': "B. Parliament",
    'C': "C. Mumbai City",
    'D': "D. Bhagwan",
    'price': 1000,
    'color': Colors.purpleAccent,
  },
  {
    'id': 2,
    'qus':
        "2. What is the new name of the Hyderabad franchise that would replace Deccan Changes in IPL6?",
    'trueAns': "D. Sun risers Hyderabad",
    'A': "A. Sun Chargers",
    'B': "B. Nizam Jyoti",
    'C': "C. Andhra Aces",
    'D': "D. Sun risers Hyderabad",
    'price': 2000,
    'color': Colors.blueAccent,
  },
  {
    'id': 3,
    'qus':
        "3. In India, under which Union Ministry does the 'Rajbhasha Vibhag' function?",
    'trueAns': "A. Home Affairs",
    'A': "A. Home Affairs",
    'B': "B. HRD",
    'C': "C. Cuiture",
    'D': "D. Law & Justice",
    'price': 3000,
    'color': Colors.red,
  },
  {
    'id': 4,
    'qus':
        "4. According to a proverb, what is said to be 'the mother of invention' ?",
    'trueAns': "D. Necessity",
    'A': "A. Society",
    'B': "B. Problem",
    'C': "C. Science",
    'D': "D. Necessity",
    'price': 5000,
    'color': Colors.yellowAccent,
  },
  {
    'id': 5,
    'qus': "5. Which actress got married to Siddharth Roy Kapur in 2012 ?",
    'trueAns': "C. Vidya Balan",
    'A': "A. Prachi Desai",
    'B': "B. Lisa Roy",
    'C': "C. Vidya Balan",
    'D': "D. Sushmita sen",
    'price': 10000,
    'color': Colors.green,
  },
  {
    'id': 6,
    'qus':
        "6. To whom did Ravindranath Tagor Dedicate his book 'visva parichay' witten on science",
    'trueAns': "B. Satyendra nath Bose",
    'A': "A. C v raman",
    'B': "B. Satyendra nath Bose",
    'C': "C. P c Royn",
    'D': "D. Jagdish Chandra Bose",
    'price': 20000,
    'color': Colors.cyan,
  },
  {
    'id': 7,
    'qus':
        "7. Which of these is a chemical element present in the periodic table?",
    'trueAns': "C. Americium",
    'A': "A. Eurocium",
    'B': "B. Asiacium",
    'C': "C. Americium",
    'D': "D. Africium",
    'price': 40000,
    'color': Colors.redAccent,
  },
  {
    'id': 8,
    'qus': "8. Which of these is not a work of Kalidas?",
    'trueAns': "B. Kadambari",
    'A': "A. Raghuvamsham",
    'B': "B. Kadambari",
    'C': "C. Vikramorvasiyam",
    'D': "D. Meghadutam",
    'price': 80000,
    'color': Colors.indigoAccent,
  },
  {
    'id': 9,
    'qus':
        "9. According to the Devi, Bhagavata, from the tears of which god is the rudraksha tree believed to have been created?",
    'trueAns': "B. Shiva",
    'A': "A. Vishnu",
    'B': "B. Shiva",
    'C': "C. Krishna",
    'D': "D. Kamadeva",
    'price': 160000,
    'color': Colors.orangeAccent,
  },
  {
    'id': 10,
    'qus': "10. Which of these names means 'gold-like'?",
    'trueAns': "C. Sonam",
    'A': "A. Sonakshi",
    'B': "B. Deepika",
    'C': "C. Sonam",
    'D': "D. Katrina",
    'price': 320000,
    'color': Colors.pinkAccent,
  },
];
